import scipy.constants as sc

from qunits.dimension import (
    Action,
    AmountOfSubstance,
    Capacitance,
    Charge,
    ElectricCurrent,
    Energy,
    Force,
    Frequency,
    Length,
    LuminousIntensity,
    MagneticInduction,
    Mass,
    Power,
    Pressure,
    Resistance,
    Temperature,
    Time,
    Velocity,
    Voltage,
)

SYMBOLS = {
    "m": Length,
    "g": Mass,
    "u": Mass,
    "s": Time,
    "A": ElectricCurrent,
    "K": Temperature,
    "mol": AmountOfSubstance,
    "cd": LuminousIntensity,
    "Hz": Frequency,
    "c": Velocity,
    "N": Force,
    "Pa": Pressure,
    "J": Energy,
    "eV": Energy,
    "W": Power,
    "h": Action,
    "V": Voltage,
    "F": Capacitance,
    "Ohm": Resistance,
    "C": Charge,
    "e": Charge,
    "T": MagneticInduction,
    "G": MagneticInduction,
}

SYMBOL_FACTORS: dict[str, tuple[float, str]] = {
    "m": (1.0, "1.0"),
    "g": (1e-3, "1e-3"),
    "u": (sc.u * 1e3, "sc.u * 1e3"),
    "s": (1.0, "1.0"),
    "A": (1.0, "1.0"),
    "K": (1.0, "1.0"),
    "mol": (1.0, "1.0"),
    "cd": (1.0, "1.0"),
    "Hz": (1.0, "1.0"),
    "c": (sc.c, "sc.c"),
    "N": (1.0, "1.0"),
    "Pa": (1.0, "1.0"),
    "J": (1.0, "1.0"),
    "eV": (sc.e, "sc.e"),
    "W": (1.0, "1.0"),
    "h": (sc.h, "sc.h"),
    "V": (1.0, "1.0"),
    "F": (1.0, "1.0"),
    "Ohm": (1.0, "1.0"),
    "C": (1.0, "1.0"),
    "e": (sc.e, "sc.e"),
    "T": (1.0, "1.0"),
    "G": (1e-4, "1e-4"),
}

SYMBOL_PREFIXES: dict[str, tuple[int, int]] = {
    "m": (-30, 3),
    "g": (-15, 3),
    "u": (0, 0),
    "s": (-30, 0),
    "A": (-15, 6),
    "K": (-15, 0),
    "mol": (-15, 3),
    "cd": (-15, 9),
    "Hz": (-15, 30),
    "c": (0, 0),
    "N": (-15, 15),
    "Pa": (-15, 15),
    "J": (-15, 15),
    "eV": (-15, 15),
    "W": (-15, 15),
    "h": (0, 0),
    "V": (-15, 9),
    "F": (-15, 3),
    "Ohm": (-15, 9),
    "C": (-15, 9),
    "e": (0, 0),
    "T": (-15, 15),
    "G": (-12, 18),
}
