# Auto-generated units with prefixes

from math import pi

import scipy.constants as sc

from qunits.dimension import (
    Action,
    AmountOfSubstance,
    Capacitance,
    Charge,
    Dimensionless,
    ElectricCurrent,
    Energy,
    Force,
    Frequency,
    Length,
    LuminousIntensity,
    MagneticInduction,
    Mass,
    Power,
    Pressure,
    Resistance,
    Temperature,
    Time,
    Velocity,
    Voltage,
)
from qunits.prefix import Context
from qunits.unit import I, Unit

__all__ = ["u"]


class u:
    """The unit registry."""

    I = I

    percent = Unit(1.0e+00 * 1e-2, frozenset({("percent", 1)}), Dimensionless, Context.I)
    nrad = Unit(1.0e-09, frozenset({("nrad", 1)}), Dimensionless, Context.ANGLE)
    urad = Unit(1.0e-06, frozenset({("urad", 1)}), Dimensionless, Context.ANGLE)
    mrad = Unit(1.0e-03, frozenset({("mrad", 1)}), Dimensionless, Context.ANGLE)
    rad = Unit(1.0e+00, frozenset({("rad", 1)}), Dimensionless, Context.ANGLE)
    pi = Unit(1.0e+00 * pi, frozenset({("pi", 1)}), Dimensionless, Context.ANGLE)
    qm = Unit(1.0e-30, frozenset({("qm", 1)}), Length, Context.I)
    rm = Unit(1.0e-27, frozenset({("rm", 1)}), Length, Context.I)
    ym = Unit(1.0e-24, frozenset({("ym", 1)}), Length, Context.I)
    zm = Unit(1.0e-21, frozenset({("zm", 1)}), Length, Context.I)
    am = Unit(1.0e-18, frozenset({("am", 1)}), Length, Context.I)
    fm = Unit(1.0e-15, frozenset({("fm", 1)}), Length, Context.I)
    pm = Unit(1.0e-12, frozenset({("pm", 1)}), Length, Context.I)
    nm = Unit(1.0e-09, frozenset({("nm", 1)}), Length, Context.I)
    um = Unit(1.0e-06, frozenset({("um", 1)}), Length, Context.I)
    mm = Unit(1.0e-03, frozenset({("mm", 1)}), Length, Context.I)
    m = Unit(1.0e+00, frozenset({("m", 1)}), Length, Context.I)
    km = Unit(1.0e+03, frozenset({("km", 1)}), Length, Context.I)
    fg = Unit(1.0e-15 * 1e-3, frozenset({("fg", 1)}), Mass, Context.I)
    pg = Unit(1.0e-12 * 1e-3, frozenset({("pg", 1)}), Mass, Context.I)
    ng = Unit(1.0e-09 * 1e-3, frozenset({("ng", 1)}), Mass, Context.I)
    ug = Unit(1.0e-06 * 1e-3, frozenset({("ug", 1)}), Mass, Context.I)
    mg = Unit(1.0e-03 * 1e-3, frozenset({("mg", 1)}), Mass, Context.I)
    g = Unit(1.0e+00 * 1e-3, frozenset({("g", 1)}), Mass, Context.I)
    kg = Unit(1.0e+03 * 1e-3, frozenset({("kg", 1)}), Mass, Context.I)
    u = Unit(1.0e+00 * sc.u * 1e3, frozenset({("u", 1)}), Mass, Context.I)
    qs = Unit(1.0e-30, frozenset({("qs", 1)}), Time, Context.I)
    rs = Unit(1.0e-27, frozenset({("rs", 1)}), Time, Context.I)
    ys = Unit(1.0e-24, frozenset({("ys", 1)}), Time, Context.I)
    zs = Unit(1.0e-21, frozenset({("zs", 1)}), Time, Context.I)
    attosecond = Unit(1.0e-18, frozenset({("attosecond", 1)}), Time, Context.I)
    fs = Unit(1.0e-15, frozenset({("fs", 1)}), Time, Context.I)
    ps = Unit(1.0e-12, frozenset({("ps", 1)}), Time, Context.I)
    ns = Unit(1.0e-09, frozenset({("ns", 1)}), Time, Context.I)
    us = Unit(1.0e-06, frozenset({("us", 1)}), Time, Context.I)
    ms = Unit(1.0e-03, frozenset({("ms", 1)}), Time, Context.I)
    s = Unit(1.0e+00, frozenset({("s", 1)}), Time, Context.I)
    fA = Unit(1.0e-15, frozenset({("fA", 1)}), ElectricCurrent, Context.I)
    pA = Unit(1.0e-12, frozenset({("pA", 1)}), ElectricCurrent, Context.I)
    nA = Unit(1.0e-09, frozenset({("nA", 1)}), ElectricCurrent, Context.I)
    uA = Unit(1.0e-06, frozenset({("uA", 1)}), ElectricCurrent, Context.I)
    mA = Unit(1.0e-03, frozenset({("mA", 1)}), ElectricCurrent, Context.I)
    A = Unit(1.0e+00, frozenset({("A", 1)}), ElectricCurrent, Context.I)
    kA = Unit(1.0e+03, frozenset({("kA", 1)}), ElectricCurrent, Context.I)
    MA = Unit(1.0e+06, frozenset({("MA", 1)}), ElectricCurrent, Context.I)
    fK = Unit(1.0e-15, frozenset({("fK", 1)}), Temperature, Context.I)
    pK = Unit(1.0e-12, frozenset({("pK", 1)}), Temperature, Context.I)
    nK = Unit(1.0e-09, frozenset({("nK", 1)}), Temperature, Context.I)
    uK = Unit(1.0e-06, frozenset({("uK", 1)}), Temperature, Context.I)
    mK = Unit(1.0e-03, frozenset({("mK", 1)}), Temperature, Context.I)
    K = Unit(1.0e+00, frozenset({("K", 1)}), Temperature, Context.I)
    fmol = Unit(1.0e-15, frozenset({("fmol", 1)}), AmountOfSubstance, Context.I)
    pmol = Unit(1.0e-12, frozenset({("pmol", 1)}), AmountOfSubstance, Context.I)
    nmol = Unit(1.0e-09, frozenset({("nmol", 1)}), AmountOfSubstance, Context.I)
    umol = Unit(1.0e-06, frozenset({("umol", 1)}), AmountOfSubstance, Context.I)
    mmol = Unit(1.0e-03, frozenset({("mmol", 1)}), AmountOfSubstance, Context.I)
    mol = Unit(1.0e+00, frozenset({("mol", 1)}), AmountOfSubstance, Context.I)
    kmol = Unit(1.0e+03, frozenset({("kmol", 1)}), AmountOfSubstance, Context.I)
    fcd = Unit(1.0e-15, frozenset({("fcd", 1)}), LuminousIntensity, Context.I)
    pcd = Unit(1.0e-12, frozenset({("pcd", 1)}), LuminousIntensity, Context.I)
    ncd = Unit(1.0e-09, frozenset({("ncd", 1)}), LuminousIntensity, Context.I)
    ucd = Unit(1.0e-06, frozenset({("ucd", 1)}), LuminousIntensity, Context.I)
    mcd = Unit(1.0e-03, frozenset({("mcd", 1)}), LuminousIntensity, Context.I)
    cd = Unit(1.0e+00, frozenset({("cd", 1)}), LuminousIntensity, Context.I)
    kcd = Unit(1.0e+03, frozenset({("kcd", 1)}), LuminousIntensity, Context.I)
    Mcd = Unit(1.0e+06, frozenset({("Mcd", 1)}), LuminousIntensity, Context.I)
    Gcd = Unit(1.0e+09, frozenset({("Gcd", 1)}), LuminousIntensity, Context.I)
    fHz = Unit(1.0e-15, frozenset({("fHz", 1)}), Frequency, Context.I)
    pHz = Unit(1.0e-12, frozenset({("pHz", 1)}), Frequency, Context.I)
    nHz = Unit(1.0e-09, frozenset({("nHz", 1)}), Frequency, Context.I)
    uHz = Unit(1.0e-06, frozenset({("uHz", 1)}), Frequency, Context.I)
    mHz = Unit(1.0e-03, frozenset({("mHz", 1)}), Frequency, Context.I)
    Hz = Unit(1.0e+00, frozenset({("Hz", 1)}), Frequency, Context.I)
    kHz = Unit(1.0e+03, frozenset({("kHz", 1)}), Frequency, Context.I)
    MHz = Unit(1.0e+06, frozenset({("MHz", 1)}), Frequency, Context.I)
    GHz = Unit(1.0e+09, frozenset({("GHz", 1)}), Frequency, Context.I)
    THz = Unit(1.0e+12, frozenset({("THz", 1)}), Frequency, Context.I)
    PHz = Unit(1.0e+15, frozenset({("PHz", 1)}), Frequency, Context.I)
    EHz = Unit(1.0e+18, frozenset({("EHz", 1)}), Frequency, Context.I)
    ZHz = Unit(1.0e+21, frozenset({("ZHz", 1)}), Frequency, Context.I)
    YHz = Unit(1.0e+24, frozenset({("YHz", 1)}), Frequency, Context.I)
    RHz = Unit(1.0e+27, frozenset({("RHz", 1)}), Frequency, Context.I)
    QHz = Unit(1.0e+30, frozenset({("QHz", 1)}), Frequency, Context.I)
    c = Unit(1.0e+00 * sc.c, frozenset({("c", 1)}), Velocity, Context.I)
    fN = Unit(1.0e-15, frozenset({("fN", 1)}), Force, Context.I)
    pN = Unit(1.0e-12, frozenset({("pN", 1)}), Force, Context.I)
    nN = Unit(1.0e-09, frozenset({("nN", 1)}), Force, Context.I)
    uN = Unit(1.0e-06, frozenset({("uN", 1)}), Force, Context.I)
    mN = Unit(1.0e-03, frozenset({("mN", 1)}), Force, Context.I)
    N = Unit(1.0e+00, frozenset({("N", 1)}), Force, Context.I)
    kN = Unit(1.0e+03, frozenset({("kN", 1)}), Force, Context.I)
    MN = Unit(1.0e+06, frozenset({("MN", 1)}), Force, Context.I)
    GN = Unit(1.0e+09, frozenset({("GN", 1)}), Force, Context.I)
    TN = Unit(1.0e+12, frozenset({("TN", 1)}), Force, Context.I)
    PN = Unit(1.0e+15, frozenset({("PN", 1)}), Force, Context.I)
    fPa = Unit(1.0e-15, frozenset({("fPa", 1)}), Pressure, Context.I)
    pPa = Unit(1.0e-12, frozenset({("pPa", 1)}), Pressure, Context.I)
    nPa = Unit(1.0e-09, frozenset({("nPa", 1)}), Pressure, Context.I)
    uPa = Unit(1.0e-06, frozenset({("uPa", 1)}), Pressure, Context.I)
    mPa = Unit(1.0e-03, frozenset({("mPa", 1)}), Pressure, Context.I)
    Pa = Unit(1.0e+00, frozenset({("Pa", 1)}), Pressure, Context.I)
    kPa = Unit(1.0e+03, frozenset({("kPa", 1)}), Pressure, Context.I)
    MPa = Unit(1.0e+06, frozenset({("MPa", 1)}), Pressure, Context.I)
    GPa = Unit(1.0e+09, frozenset({("GPa", 1)}), Pressure, Context.I)
    TPa = Unit(1.0e+12, frozenset({("TPa", 1)}), Pressure, Context.I)
    PPa = Unit(1.0e+15, frozenset({("PPa", 1)}), Pressure, Context.I)
    fJ = Unit(1.0e-15, frozenset({("fJ", 1)}), Energy, Context.I)
    pJ = Unit(1.0e-12, frozenset({("pJ", 1)}), Energy, Context.I)
    nJ = Unit(1.0e-09, frozenset({("nJ", 1)}), Energy, Context.I)
    uJ = Unit(1.0e-06, frozenset({("uJ", 1)}), Energy, Context.I)
    mJ = Unit(1.0e-03, frozenset({("mJ", 1)}), Energy, Context.I)
    J = Unit(1.0e+00, frozenset({("J", 1)}), Energy, Context.I)
    kJ = Unit(1.0e+03, frozenset({("kJ", 1)}), Energy, Context.I)
    MJ = Unit(1.0e+06, frozenset({("MJ", 1)}), Energy, Context.I)
    GJ = Unit(1.0e+09, frozenset({("GJ", 1)}), Energy, Context.I)
    TJ = Unit(1.0e+12, frozenset({("TJ", 1)}), Energy, Context.I)
    PJ = Unit(1.0e+15, frozenset({("PJ", 1)}), Energy, Context.I)
    feV = Unit(1.0e-15 * sc.e, frozenset({("feV", 1)}), Energy, Context.I)
    peV = Unit(1.0e-12 * sc.e, frozenset({("peV", 1)}), Energy, Context.I)
    neV = Unit(1.0e-09 * sc.e, frozenset({("neV", 1)}), Energy, Context.I)
    ueV = Unit(1.0e-06 * sc.e, frozenset({("ueV", 1)}), Energy, Context.I)
    meV = Unit(1.0e-03 * sc.e, frozenset({("meV", 1)}), Energy, Context.I)
    eV = Unit(1.0e+00 * sc.e, frozenset({("eV", 1)}), Energy, Context.I)
    keV = Unit(1.0e+03 * sc.e, frozenset({("keV", 1)}), Energy, Context.I)
    MeV = Unit(1.0e+06 * sc.e, frozenset({("MeV", 1)}), Energy, Context.I)
    GeV = Unit(1.0e+09 * sc.e, frozenset({("GeV", 1)}), Energy, Context.I)
    TeV = Unit(1.0e+12 * sc.e, frozenset({("TeV", 1)}), Energy, Context.I)
    PeV = Unit(1.0e+15 * sc.e, frozenset({("PeV", 1)}), Energy, Context.I)
    fW = Unit(1.0e-15, frozenset({("fW", 1)}), Power, Context.I)
    pW = Unit(1.0e-12, frozenset({("pW", 1)}), Power, Context.I)
    nW = Unit(1.0e-09, frozenset({("nW", 1)}), Power, Context.I)
    uW = Unit(1.0e-06, frozenset({("uW", 1)}), Power, Context.I)
    mW = Unit(1.0e-03, frozenset({("mW", 1)}), Power, Context.I)
    W = Unit(1.0e+00, frozenset({("W", 1)}), Power, Context.I)
    kW = Unit(1.0e+03, frozenset({("kW", 1)}), Power, Context.I)
    MW = Unit(1.0e+06, frozenset({("MW", 1)}), Power, Context.I)
    GW = Unit(1.0e+09, frozenset({("GW", 1)}), Power, Context.I)
    TW = Unit(1.0e+12, frozenset({("TW", 1)}), Power, Context.I)
    PW = Unit(1.0e+15, frozenset({("PW", 1)}), Power, Context.I)
    h = Unit(1.0e+00 * sc.h, frozenset({("h", 1)}), Action, Context.I)
    fV = Unit(1.0e-15, frozenset({("fV", 1)}), Voltage, Context.I)
    pV = Unit(1.0e-12, frozenset({("pV", 1)}), Voltage, Context.I)
    nV = Unit(1.0e-09, frozenset({("nV", 1)}), Voltage, Context.I)
    uV = Unit(1.0e-06, frozenset({("uV", 1)}), Voltage, Context.I)
    mV = Unit(1.0e-03, frozenset({("mV", 1)}), Voltage, Context.I)
    V = Unit(1.0e+00, frozenset({("V", 1)}), Voltage, Context.I)
    kV = Unit(1.0e+03, frozenset({("kV", 1)}), Voltage, Context.I)
    MV = Unit(1.0e+06, frozenset({("MV", 1)}), Voltage, Context.I)
    GV = Unit(1.0e+09, frozenset({("GV", 1)}), Voltage, Context.I)
    fF = Unit(1.0e-15, frozenset({("fF", 1)}), Capacitance, Context.I)
    pF = Unit(1.0e-12, frozenset({("pF", 1)}), Capacitance, Context.I)
    nF = Unit(1.0e-09, frozenset({("nF", 1)}), Capacitance, Context.I)
    uF = Unit(1.0e-06, frozenset({("uF", 1)}), Capacitance, Context.I)
    mF = Unit(1.0e-03, frozenset({("mF", 1)}), Capacitance, Context.I)
    F = Unit(1.0e+00, frozenset({("F", 1)}), Capacitance, Context.I)
    kF = Unit(1.0e+03, frozenset({("kF", 1)}), Capacitance, Context.I)
    fOhm = Unit(1.0e-15, frozenset({("fOhm", 1)}), Resistance, Context.I)
    pOhm = Unit(1.0e-12, frozenset({("pOhm", 1)}), Resistance, Context.I)
    nOhm = Unit(1.0e-09, frozenset({("nOhm", 1)}), Resistance, Context.I)
    uOhm = Unit(1.0e-06, frozenset({("uOhm", 1)}), Resistance, Context.I)
    mOhm = Unit(1.0e-03, frozenset({("mOhm", 1)}), Resistance, Context.I)
    Ohm = Unit(1.0e+00, frozenset({("Ohm", 1)}), Resistance, Context.I)
    kOhm = Unit(1.0e+03, frozenset({("kOhm", 1)}), Resistance, Context.I)
    MOhm = Unit(1.0e+06, frozenset({("MOhm", 1)}), Resistance, Context.I)
    GOhm = Unit(1.0e+09, frozenset({("GOhm", 1)}), Resistance, Context.I)
    fC = Unit(1.0e-15, frozenset({("fC", 1)}), Charge, Context.I)
    pC = Unit(1.0e-12, frozenset({("pC", 1)}), Charge, Context.I)
    nC = Unit(1.0e-09, frozenset({("nC", 1)}), Charge, Context.I)
    uC = Unit(1.0e-06, frozenset({("uC", 1)}), Charge, Context.I)
    mC = Unit(1.0e-03, frozenset({("mC", 1)}), Charge, Context.I)
    C = Unit(1.0e+00, frozenset({("C", 1)}), Charge, Context.I)
    kC = Unit(1.0e+03, frozenset({("kC", 1)}), Charge, Context.I)
    MC = Unit(1.0e+06, frozenset({("MC", 1)}), Charge, Context.I)
    GC = Unit(1.0e+09, frozenset({("GC", 1)}), Charge, Context.I)
    e = Unit(1.0e+00 * sc.e, frozenset({("e", 1)}), Charge, Context.I)
    fT = Unit(1.0e-15, frozenset({("fT", 1)}), MagneticInduction, Context.I)
    pT = Unit(1.0e-12, frozenset({("pT", 1)}), MagneticInduction, Context.I)
    nT = Unit(1.0e-09, frozenset({("nT", 1)}), MagneticInduction, Context.I)
    uT = Unit(1.0e-06, frozenset({("uT", 1)}), MagneticInduction, Context.I)
    mT = Unit(1.0e-03, frozenset({("mT", 1)}), MagneticInduction, Context.I)
    T = Unit(1.0e+00, frozenset({("T", 1)}), MagneticInduction, Context.I)
    kT = Unit(1.0e+03, frozenset({("kT", 1)}), MagneticInduction, Context.I)
    MT = Unit(1.0e+06, frozenset({("MT", 1)}), MagneticInduction, Context.I)
    GT = Unit(1.0e+09, frozenset({("GT", 1)}), MagneticInduction, Context.I)
    TT = Unit(1.0e+12, frozenset({("TT", 1)}), MagneticInduction, Context.I)
    PT = Unit(1.0e+15, frozenset({("PT", 1)}), MagneticInduction, Context.I)
    pG = Unit(1.0e-12 * 1e-4, frozenset({("pG", 1)}), MagneticInduction, Context.I)
    nG = Unit(1.0e-09 * 1e-4, frozenset({("nG", 1)}), MagneticInduction, Context.I)
    uG = Unit(1.0e-06 * 1e-4, frozenset({("uG", 1)}), MagneticInduction, Context.I)
    mG = Unit(1.0e-03 * 1e-4, frozenset({("mG", 1)}), MagneticInduction, Context.I)
    G = Unit(1.0e+00 * 1e-4, frozenset({("G", 1)}), MagneticInduction, Context.I)
    kG = Unit(1.0e+03 * 1e-4, frozenset({("kG", 1)}), MagneticInduction, Context.I)
    MG = Unit(1.0e+06 * 1e-4, frozenset({("MG", 1)}), MagneticInduction, Context.I)
    GG = Unit(1.0e+09 * 1e-4, frozenset({("GG", 1)}), MagneticInduction, Context.I)
    TG = Unit(1.0e+12 * 1e-4, frozenset({("TG", 1)}), MagneticInduction, Context.I)
    PG = Unit(1.0e+15 * 1e-4, frozenset({("PG", 1)}), MagneticInduction, Context.I)
    EG = Unit(1.0e+18 * 1e-4, frozenset({("EG", 1)}), MagneticInduction, Context.I)
