# Auto-generated units with prefixes

from qunits.dimension import (
    AmountOfSubstance,
    Charge,
    ElectricCurrent,
    Force,
    Frequency,
    Length,
    LuminousIntensity,
    MagneticInduction,
    Mass,
    Pressure,
    Temperature,
    Time,
)
from qunits.unit import Unit


class si:
    """The SI unit system."""

    qm = Unit(1.0e-30, Length, symbol="m", prefix_exp=-30)
    rm = Unit(1.0e-27, Length, symbol="m", prefix_exp=-27)
    ym = Unit(1.0e-24, Length, symbol="m", prefix_exp=-24)
    zm = Unit(1.0e-21, Length, symbol="m", prefix_exp=-21)
    am = Unit(1.0e-18, Length, symbol="m", prefix_exp=-18)
    fm = Unit(1.0e-15, Length, symbol="m", prefix_exp=-15)
    pm = Unit(1.0e-12, Length, symbol="m", prefix_exp=-12)
    nm = Unit(1.0e-09, Length, symbol="m", prefix_exp=-9)
    um = Unit(1.0e-06, Length, symbol="m", prefix_exp=-6)
    mm = Unit(1.0e-03, Length, symbol="m", prefix_exp=-3)
    m = Unit(1.0e00, Length, symbol="m", prefix_exp=0)
    km = Unit(1.0e03, Length, symbol="m", prefix_exp=3)
    fg = Unit(1.0e-15, Mass, symbol="g", prefix_exp=-15)
    pg = Unit(1.0e-12, Mass, symbol="g", prefix_exp=-12)
    ng = Unit(1.0e-09, Mass, symbol="g", prefix_exp=-9)
    ug = Unit(1.0e-06, Mass, symbol="g", prefix_exp=-6)
    mg = Unit(1.0e-03, Mass, symbol="g", prefix_exp=-3)
    g = Unit(1.0e00, Mass, symbol="g", prefix_exp=0)
    kg = Unit(1.0e03, Mass, symbol="g", prefix_exp=3)
    u = Unit(1.7e-24, Mass, symbol="u", prefix_exp=0)
    qs = Unit(1.0e-30, Time, symbol="s", prefix_exp=-30)
    rs = Unit(1.0e-27, Time, symbol="s", prefix_exp=-27)
    ys = Unit(1.0e-24, Time, symbol="s", prefix_exp=-24)
    zs = Unit(1.0e-21, Time, symbol="s", prefix_exp=-21)
    attosecond = Unit(1.0e-18, Time, symbol="s", prefix_exp=-18)
    fs = Unit(1.0e-15, Time, symbol="s", prefix_exp=-15)
    ps = Unit(1.0e-12, Time, symbol="s", prefix_exp=-12)
    ns = Unit(1.0e-09, Time, symbol="s", prefix_exp=-9)
    us = Unit(1.0e-06, Time, symbol="s", prefix_exp=-6)
    ms = Unit(1.0e-03, Time, symbol="s", prefix_exp=-3)
    s = Unit(1.0e00, Time, symbol="s", prefix_exp=0)
    fA = Unit(1.0e-15, ElectricCurrent, symbol="A", prefix_exp=-15)
    pA = Unit(1.0e-12, ElectricCurrent, symbol="A", prefix_exp=-12)
    nA = Unit(1.0e-09, ElectricCurrent, symbol="A", prefix_exp=-9)
    uA = Unit(1.0e-06, ElectricCurrent, symbol="A", prefix_exp=-6)
    mA = Unit(1.0e-03, ElectricCurrent, symbol="A", prefix_exp=-3)
    A = Unit(1.0e00, ElectricCurrent, symbol="A", prefix_exp=0)
    kA = Unit(1.0e03, ElectricCurrent, symbol="A", prefix_exp=3)
    MA = Unit(1.0e06, ElectricCurrent, symbol="A", prefix_exp=6)
    fK = Unit(1.0e-15, Temperature, symbol="K", prefix_exp=-15)
    pK = Unit(1.0e-12, Temperature, symbol="K", prefix_exp=-12)
    nK = Unit(1.0e-09, Temperature, symbol="K", prefix_exp=-9)
    uK = Unit(1.0e-06, Temperature, symbol="K", prefix_exp=-6)
    mK = Unit(1.0e-03, Temperature, symbol="K", prefix_exp=-3)
    K = Unit(1.0e00, Temperature, symbol="K", prefix_exp=0)
    fmol = Unit(1.0e-15, AmountOfSubstance, symbol="mol", prefix_exp=-15)
    pmol = Unit(1.0e-12, AmountOfSubstance, symbol="mol", prefix_exp=-12)
    nmol = Unit(1.0e-09, AmountOfSubstance, symbol="mol", prefix_exp=-9)
    umol = Unit(1.0e-06, AmountOfSubstance, symbol="mol", prefix_exp=-6)
    mmol = Unit(1.0e-03, AmountOfSubstance, symbol="mol", prefix_exp=-3)
    mol = Unit(1.0e00, AmountOfSubstance, symbol="mol", prefix_exp=0)
    kmol = Unit(1.0e03, AmountOfSubstance, symbol="mol", prefix_exp=3)
    fcd = Unit(1.0e-15, LuminousIntensity, symbol="cd", prefix_exp=-15)
    pcd = Unit(1.0e-12, LuminousIntensity, symbol="cd", prefix_exp=-12)
    ncd = Unit(1.0e-09, LuminousIntensity, symbol="cd", prefix_exp=-9)
    ucd = Unit(1.0e-06, LuminousIntensity, symbol="cd", prefix_exp=-6)
    mcd = Unit(1.0e-03, LuminousIntensity, symbol="cd", prefix_exp=-3)
    cd = Unit(1.0e00, LuminousIntensity, symbol="cd", prefix_exp=0)
    kcd = Unit(1.0e03, LuminousIntensity, symbol="cd", prefix_exp=3)
    Mcd = Unit(1.0e06, LuminousIntensity, symbol="cd", prefix_exp=6)
    Gcd = Unit(1.0e09, LuminousIntensity, symbol="cd", prefix_exp=9)
    fHz = Unit(1.0e-15, Frequency, symbol="Hz", prefix_exp=-15)
    pHz = Unit(1.0e-12, Frequency, symbol="Hz", prefix_exp=-12)
    nHz = Unit(1.0e-09, Frequency, symbol="Hz", prefix_exp=-9)
    uHz = Unit(1.0e-06, Frequency, symbol="Hz", prefix_exp=-6)
    mHz = Unit(1.0e-03, Frequency, symbol="Hz", prefix_exp=-3)
    Hz = Unit(1.0e00, Frequency, symbol="Hz", prefix_exp=0)
    kHz = Unit(1.0e03, Frequency, symbol="Hz", prefix_exp=3)
    MHz = Unit(1.0e06, Frequency, symbol="Hz", prefix_exp=6)
    GHz = Unit(1.0e09, Frequency, symbol="Hz", prefix_exp=9)
    THz = Unit(1.0e12, Frequency, symbol="Hz", prefix_exp=12)
    PHz = Unit(1.0e15, Frequency, symbol="Hz", prefix_exp=15)
    EHz = Unit(1.0e18, Frequency, symbol="Hz", prefix_exp=18)
    ZHz = Unit(1.0e21, Frequency, symbol="Hz", prefix_exp=21)
    YHz = Unit(1.0e24, Frequency, symbol="Hz", prefix_exp=24)
    RHz = Unit(1.0e27, Frequency, symbol="Hz", prefix_exp=27)
    QHz = Unit(1.0e30, Frequency, symbol="Hz", prefix_exp=30)
    fN = Unit(1.0e-15, Force, symbol="N", prefix_exp=-15)
    pN = Unit(1.0e-12, Force, symbol="N", prefix_exp=-12)
    nN = Unit(1.0e-09, Force, symbol="N", prefix_exp=-9)
    uN = Unit(1.0e-06, Force, symbol="N", prefix_exp=-6)
    mN = Unit(1.0e-03, Force, symbol="N", prefix_exp=-3)
    N = Unit(1.0e00, Force, symbol="N", prefix_exp=0)
    kN = Unit(1.0e03, Force, symbol="N", prefix_exp=3)
    MN = Unit(1.0e06, Force, symbol="N", prefix_exp=6)
    GN = Unit(1.0e09, Force, symbol="N", prefix_exp=9)
    TN = Unit(1.0e12, Force, symbol="N", prefix_exp=12)
    PN = Unit(1.0e15, Force, symbol="N", prefix_exp=15)
    fPa = Unit(1.0e-15, Pressure, symbol="Pa", prefix_exp=-15)
    pPa = Unit(1.0e-12, Pressure, symbol="Pa", prefix_exp=-12)
    nPa = Unit(1.0e-09, Pressure, symbol="Pa", prefix_exp=-9)
    uPa = Unit(1.0e-06, Pressure, symbol="Pa", prefix_exp=-6)
    mPa = Unit(1.0e-03, Pressure, symbol="Pa", prefix_exp=-3)
    Pa = Unit(1.0e00, Pressure, symbol="Pa", prefix_exp=0)
    kPa = Unit(1.0e03, Pressure, symbol="Pa", prefix_exp=3)
    MPa = Unit(1.0e06, Pressure, symbol="Pa", prefix_exp=6)
    GPa = Unit(1.0e09, Pressure, symbol="Pa", prefix_exp=9)
    TPa = Unit(1.0e12, Pressure, symbol="Pa", prefix_exp=12)
    PPa = Unit(1.0e15, Pressure, symbol="Pa", prefix_exp=15)
    fC = Unit(1.0e-15, Charge, symbol="C", prefix_exp=-15)
    pC = Unit(1.0e-12, Charge, symbol="C", prefix_exp=-12)
    nC = Unit(1.0e-09, Charge, symbol="C", prefix_exp=-9)
    uC = Unit(1.0e-06, Charge, symbol="C", prefix_exp=-6)
    mC = Unit(1.0e-03, Charge, symbol="C", prefix_exp=-3)
    C = Unit(1.0e00, Charge, symbol="C", prefix_exp=0)
    kC = Unit(1.0e03, Charge, symbol="C", prefix_exp=3)
    MC = Unit(1.0e06, Charge, symbol="C", prefix_exp=6)
    GC = Unit(1.0e09, Charge, symbol="C", prefix_exp=9)
    fT = Unit(1.0e-15, MagneticInduction, symbol="T", prefix_exp=-15)
    pT = Unit(1.0e-12, MagneticInduction, symbol="T", prefix_exp=-12)
    nT = Unit(1.0e-09, MagneticInduction, symbol="T", prefix_exp=-9)
    uT = Unit(1.0e-06, MagneticInduction, symbol="T", prefix_exp=-6)
    mT = Unit(1.0e-03, MagneticInduction, symbol="T", prefix_exp=-3)
    T = Unit(1.0e00, MagneticInduction, symbol="T", prefix_exp=0)
    kT = Unit(1.0e03, MagneticInduction, symbol="T", prefix_exp=3)
    MT = Unit(1.0e06, MagneticInduction, symbol="T", prefix_exp=6)
    GT = Unit(1.0e09, MagneticInduction, symbol="T", prefix_exp=9)
    TT = Unit(1.0e12, MagneticInduction, symbol="T", prefix_exp=12)
    PT = Unit(1.0e15, MagneticInduction, symbol="T", prefix_exp=15)
    pG = Unit(1.0e-16, MagneticInduction, symbol="G", prefix_exp=-12)
    nG = Unit(1.0e-13, MagneticInduction, symbol="G", prefix_exp=-9)
    uG = Unit(1.0e-10, MagneticInduction, symbol="G", prefix_exp=-6)
    mG = Unit(1.0e-07, MagneticInduction, symbol="G", prefix_exp=-3)
    G = Unit(1.0e-04, MagneticInduction, symbol="G", prefix_exp=0)
    kG = Unit(1.0e-01, MagneticInduction, symbol="G", prefix_exp=3)
    MG = Unit(1.0e02, MagneticInduction, symbol="G", prefix_exp=6)
    GG = Unit(1.0e05, MagneticInduction, symbol="G", prefix_exp=9)
    TG = Unit(1.0e08, MagneticInduction, symbol="G", prefix_exp=12)
    PG = Unit(1.0e11, MagneticInduction, symbol="G", prefix_exp=15)
    EG = Unit(1.0e14, MagneticInduction, symbol="G", prefix_exp=18)
