# Auto-generated units with prefixes

import scipy.constants as sc

from qunits.dimension import (
    Action,
    AmountOfSubstance,
    Capacitance,
    Charge,
    ElectricCurrent,
    Energy,
    Force,
    Frequency,
    Length,
    LuminousIntensity,
    MagneticInduction,
    Mass,
    Power,
    Pressure,
    Resistance,
    Temperature,
    Time,
    Velocity,
    Voltage,
)
from qunits.unit import Unit


class u:
    """The unit system."""

    qm = Unit(1.0e-30, Length, symbol="m", prefix_exp=-30)
    rm = Unit(1.0e-27, Length, symbol="m", prefix_exp=-27)
    ym = Unit(1.0e-24, Length, symbol="m", prefix_exp=-24)
    zm = Unit(1.0e-21, Length, symbol="m", prefix_exp=-21)
    am = Unit(1.0e-18, Length, symbol="m", prefix_exp=-18)
    fm = Unit(1.0e-15, Length, symbol="m", prefix_exp=-15)
    pm = Unit(1.0e-12, Length, symbol="m", prefix_exp=-12)
    nm = Unit(1.0e-09, Length, symbol="m", prefix_exp=-9)
    um = Unit(1.0e-06, Length, symbol="m", prefix_exp=-6)
    mm = Unit(1.0e-03, Length, symbol="m", prefix_exp=-3)
    m = Unit(1.0e+00, Length, symbol="m", prefix_exp=0)
    km = Unit(1.0e+03, Length, symbol="m", prefix_exp=3)
    fg = Unit(1.0e-15 * 1e-3, Mass, symbol="g", prefix_exp=-15)
    pg = Unit(1.0e-12 * 1e-3, Mass, symbol="g", prefix_exp=-12)
    ng = Unit(1.0e-09 * 1e-3, Mass, symbol="g", prefix_exp=-9)
    ug = Unit(1.0e-06 * 1e-3, Mass, symbol="g", prefix_exp=-6)
    mg = Unit(1.0e-03 * 1e-3, Mass, symbol="g", prefix_exp=-3)
    g = Unit(1.0e+00 * 1e-3, Mass, symbol="g", prefix_exp=0)
    kg = Unit(1.0e+03 * 1e-3, Mass, symbol="g", prefix_exp=3)
    u = Unit(1.0e+00 * sc.u * 1e3, Mass, symbol="u", prefix_exp=0)
    qs = Unit(1.0e-30, Time, symbol="s", prefix_exp=-30)
    rs = Unit(1.0e-27, Time, symbol="s", prefix_exp=-27)
    ys = Unit(1.0e-24, Time, symbol="s", prefix_exp=-24)
    zs = Unit(1.0e-21, Time, symbol="s", prefix_exp=-21)
    attosecond = Unit(1.0e-18, Time, symbol="s", prefix_exp=-18)
    fs = Unit(1.0e-15, Time, symbol="s", prefix_exp=-15)
    ps = Unit(1.0e-12, Time, symbol="s", prefix_exp=-12)
    ns = Unit(1.0e-09, Time, symbol="s", prefix_exp=-9)
    us = Unit(1.0e-06, Time, symbol="s", prefix_exp=-6)
    ms = Unit(1.0e-03, Time, symbol="s", prefix_exp=-3)
    s = Unit(1.0e+00, Time, symbol="s", prefix_exp=0)
    fA = Unit(1.0e-15, ElectricCurrent, symbol="A", prefix_exp=-15)
    pA = Unit(1.0e-12, ElectricCurrent, symbol="A", prefix_exp=-12)
    nA = Unit(1.0e-09, ElectricCurrent, symbol="A", prefix_exp=-9)
    uA = Unit(1.0e-06, ElectricCurrent, symbol="A", prefix_exp=-6)
    mA = Unit(1.0e-03, ElectricCurrent, symbol="A", prefix_exp=-3)
    A = Unit(1.0e+00, ElectricCurrent, symbol="A", prefix_exp=0)
    kA = Unit(1.0e+03, ElectricCurrent, symbol="A", prefix_exp=3)
    MA = Unit(1.0e+06, ElectricCurrent, symbol="A", prefix_exp=6)
    fK = Unit(1.0e-15, Temperature, symbol="K", prefix_exp=-15)
    pK = Unit(1.0e-12, Temperature, symbol="K", prefix_exp=-12)
    nK = Unit(1.0e-09, Temperature, symbol="K", prefix_exp=-9)
    uK = Unit(1.0e-06, Temperature, symbol="K", prefix_exp=-6)
    mK = Unit(1.0e-03, Temperature, symbol="K", prefix_exp=-3)
    K = Unit(1.0e+00, Temperature, symbol="K", prefix_exp=0)
    fmol = Unit(1.0e-15, AmountOfSubstance, symbol="mol", prefix_exp=-15)
    pmol = Unit(1.0e-12, AmountOfSubstance, symbol="mol", prefix_exp=-12)
    nmol = Unit(1.0e-09, AmountOfSubstance, symbol="mol", prefix_exp=-9)
    umol = Unit(1.0e-06, AmountOfSubstance, symbol="mol", prefix_exp=-6)
    mmol = Unit(1.0e-03, AmountOfSubstance, symbol="mol", prefix_exp=-3)
    mol = Unit(1.0e+00, AmountOfSubstance, symbol="mol", prefix_exp=0)
    kmol = Unit(1.0e+03, AmountOfSubstance, symbol="mol", prefix_exp=3)
    fcd = Unit(1.0e-15, LuminousIntensity, symbol="cd", prefix_exp=-15)
    pcd = Unit(1.0e-12, LuminousIntensity, symbol="cd", prefix_exp=-12)
    ncd = Unit(1.0e-09, LuminousIntensity, symbol="cd", prefix_exp=-9)
    ucd = Unit(1.0e-06, LuminousIntensity, symbol="cd", prefix_exp=-6)
    mcd = Unit(1.0e-03, LuminousIntensity, symbol="cd", prefix_exp=-3)
    cd = Unit(1.0e+00, LuminousIntensity, symbol="cd", prefix_exp=0)
    kcd = Unit(1.0e+03, LuminousIntensity, symbol="cd", prefix_exp=3)
    Mcd = Unit(1.0e+06, LuminousIntensity, symbol="cd", prefix_exp=6)
    Gcd = Unit(1.0e+09, LuminousIntensity, symbol="cd", prefix_exp=9)
    fHz = Unit(1.0e-15, Frequency, symbol="Hz", prefix_exp=-15)
    pHz = Unit(1.0e-12, Frequency, symbol="Hz", prefix_exp=-12)
    nHz = Unit(1.0e-09, Frequency, symbol="Hz", prefix_exp=-9)
    uHz = Unit(1.0e-06, Frequency, symbol="Hz", prefix_exp=-6)
    mHz = Unit(1.0e-03, Frequency, symbol="Hz", prefix_exp=-3)
    Hz = Unit(1.0e+00, Frequency, symbol="Hz", prefix_exp=0)
    kHz = Unit(1.0e+03, Frequency, symbol="Hz", prefix_exp=3)
    MHz = Unit(1.0e+06, Frequency, symbol="Hz", prefix_exp=6)
    GHz = Unit(1.0e+09, Frequency, symbol="Hz", prefix_exp=9)
    THz = Unit(1.0e+12, Frequency, symbol="Hz", prefix_exp=12)
    PHz = Unit(1.0e+15, Frequency, symbol="Hz", prefix_exp=15)
    EHz = Unit(1.0e+18, Frequency, symbol="Hz", prefix_exp=18)
    ZHz = Unit(1.0e+21, Frequency, symbol="Hz", prefix_exp=21)
    YHz = Unit(1.0e+24, Frequency, symbol="Hz", prefix_exp=24)
    RHz = Unit(1.0e+27, Frequency, symbol="Hz", prefix_exp=27)
    QHz = Unit(1.0e+30, Frequency, symbol="Hz", prefix_exp=30)
    c = Unit(1.0e+00 * sc.c, Velocity, symbol="c", prefix_exp=0)
    fN = Unit(1.0e-15, Force, symbol="N", prefix_exp=-15)
    pN = Unit(1.0e-12, Force, symbol="N", prefix_exp=-12)
    nN = Unit(1.0e-09, Force, symbol="N", prefix_exp=-9)
    uN = Unit(1.0e-06, Force, symbol="N", prefix_exp=-6)
    mN = Unit(1.0e-03, Force, symbol="N", prefix_exp=-3)
    N = Unit(1.0e+00, Force, symbol="N", prefix_exp=0)
    kN = Unit(1.0e+03, Force, symbol="N", prefix_exp=3)
    MN = Unit(1.0e+06, Force, symbol="N", prefix_exp=6)
    GN = Unit(1.0e+09, Force, symbol="N", prefix_exp=9)
    TN = Unit(1.0e+12, Force, symbol="N", prefix_exp=12)
    PN = Unit(1.0e+15, Force, symbol="N", prefix_exp=15)
    fPa = Unit(1.0e-15, Pressure, symbol="Pa", prefix_exp=-15)
    pPa = Unit(1.0e-12, Pressure, symbol="Pa", prefix_exp=-12)
    nPa = Unit(1.0e-09, Pressure, symbol="Pa", prefix_exp=-9)
    uPa = Unit(1.0e-06, Pressure, symbol="Pa", prefix_exp=-6)
    mPa = Unit(1.0e-03, Pressure, symbol="Pa", prefix_exp=-3)
    Pa = Unit(1.0e+00, Pressure, symbol="Pa", prefix_exp=0)
    kPa = Unit(1.0e+03, Pressure, symbol="Pa", prefix_exp=3)
    MPa = Unit(1.0e+06, Pressure, symbol="Pa", prefix_exp=6)
    GPa = Unit(1.0e+09, Pressure, symbol="Pa", prefix_exp=9)
    TPa = Unit(1.0e+12, Pressure, symbol="Pa", prefix_exp=12)
    PPa = Unit(1.0e+15, Pressure, symbol="Pa", prefix_exp=15)
    fJ = Unit(1.0e-15, Energy, symbol="J", prefix_exp=-15)
    pJ = Unit(1.0e-12, Energy, symbol="J", prefix_exp=-12)
    nJ = Unit(1.0e-09, Energy, symbol="J", prefix_exp=-9)
    uJ = Unit(1.0e-06, Energy, symbol="J", prefix_exp=-6)
    mJ = Unit(1.0e-03, Energy, symbol="J", prefix_exp=-3)
    J = Unit(1.0e+00, Energy, symbol="J", prefix_exp=0)
    kJ = Unit(1.0e+03, Energy, symbol="J", prefix_exp=3)
    MJ = Unit(1.0e+06, Energy, symbol="J", prefix_exp=6)
    GJ = Unit(1.0e+09, Energy, symbol="J", prefix_exp=9)
    TJ = Unit(1.0e+12, Energy, symbol="J", prefix_exp=12)
    PJ = Unit(1.0e+15, Energy, symbol="J", prefix_exp=15)
    feV = Unit(1.0e-15 * sc.e, Energy, symbol="eV", prefix_exp=-15)
    peV = Unit(1.0e-12 * sc.e, Energy, symbol="eV", prefix_exp=-12)
    neV = Unit(1.0e-09 * sc.e, Energy, symbol="eV", prefix_exp=-9)
    ueV = Unit(1.0e-06 * sc.e, Energy, symbol="eV", prefix_exp=-6)
    meV = Unit(1.0e-03 * sc.e, Energy, symbol="eV", prefix_exp=-3)
    eV = Unit(1.0e+00 * sc.e, Energy, symbol="eV", prefix_exp=0)
    keV = Unit(1.0e+03 * sc.e, Energy, symbol="eV", prefix_exp=3)
    MeV = Unit(1.0e+06 * sc.e, Energy, symbol="eV", prefix_exp=6)
    GeV = Unit(1.0e+09 * sc.e, Energy, symbol="eV", prefix_exp=9)
    TeV = Unit(1.0e+12 * sc.e, Energy, symbol="eV", prefix_exp=12)
    PeV = Unit(1.0e+15 * sc.e, Energy, symbol="eV", prefix_exp=15)
    fW = Unit(1.0e-15, Power, symbol="W", prefix_exp=-15)
    pW = Unit(1.0e-12, Power, symbol="W", prefix_exp=-12)
    nW = Unit(1.0e-09, Power, symbol="W", prefix_exp=-9)
    uW = Unit(1.0e-06, Power, symbol="W", prefix_exp=-6)
    mW = Unit(1.0e-03, Power, symbol="W", prefix_exp=-3)
    W = Unit(1.0e+00, Power, symbol="W", prefix_exp=0)
    kW = Unit(1.0e+03, Power, symbol="W", prefix_exp=3)
    MW = Unit(1.0e+06, Power, symbol="W", prefix_exp=6)
    GW = Unit(1.0e+09, Power, symbol="W", prefix_exp=9)
    TW = Unit(1.0e+12, Power, symbol="W", prefix_exp=12)
    PW = Unit(1.0e+15, Power, symbol="W", prefix_exp=15)
    h = Unit(1.0e+00 * sc.h, Action, symbol="h", prefix_exp=0)
    fV = Unit(1.0e-15, Voltage, symbol="V", prefix_exp=-15)
    pV = Unit(1.0e-12, Voltage, symbol="V", prefix_exp=-12)
    nV = Unit(1.0e-09, Voltage, symbol="V", prefix_exp=-9)
    uV = Unit(1.0e-06, Voltage, symbol="V", prefix_exp=-6)
    mV = Unit(1.0e-03, Voltage, symbol="V", prefix_exp=-3)
    V = Unit(1.0e+00, Voltage, symbol="V", prefix_exp=0)
    kV = Unit(1.0e+03, Voltage, symbol="V", prefix_exp=3)
    MV = Unit(1.0e+06, Voltage, symbol="V", prefix_exp=6)
    GV = Unit(1.0e+09, Voltage, symbol="V", prefix_exp=9)
    fF = Unit(1.0e-15, Capacitance, symbol="F", prefix_exp=-15)
    pF = Unit(1.0e-12, Capacitance, symbol="F", prefix_exp=-12)
    nF = Unit(1.0e-09, Capacitance, symbol="F", prefix_exp=-9)
    uF = Unit(1.0e-06, Capacitance, symbol="F", prefix_exp=-6)
    mF = Unit(1.0e-03, Capacitance, symbol="F", prefix_exp=-3)
    F = Unit(1.0e+00, Capacitance, symbol="F", prefix_exp=0)
    kF = Unit(1.0e+03, Capacitance, symbol="F", prefix_exp=3)
    fOhm = Unit(1.0e-15, Resistance, symbol="Ohm", prefix_exp=-15)
    pOhm = Unit(1.0e-12, Resistance, symbol="Ohm", prefix_exp=-12)
    nOhm = Unit(1.0e-09, Resistance, symbol="Ohm", prefix_exp=-9)
    uOhm = Unit(1.0e-06, Resistance, symbol="Ohm", prefix_exp=-6)
    mOhm = Unit(1.0e-03, Resistance, symbol="Ohm", prefix_exp=-3)
    Ohm = Unit(1.0e+00, Resistance, symbol="Ohm", prefix_exp=0)
    kOhm = Unit(1.0e+03, Resistance, symbol="Ohm", prefix_exp=3)
    MOhm = Unit(1.0e+06, Resistance, symbol="Ohm", prefix_exp=6)
    GOhm = Unit(1.0e+09, Resistance, symbol="Ohm", prefix_exp=9)
    fC = Unit(1.0e-15, Charge, symbol="C", prefix_exp=-15)
    pC = Unit(1.0e-12, Charge, symbol="C", prefix_exp=-12)
    nC = Unit(1.0e-09, Charge, symbol="C", prefix_exp=-9)
    uC = Unit(1.0e-06, Charge, symbol="C", prefix_exp=-6)
    mC = Unit(1.0e-03, Charge, symbol="C", prefix_exp=-3)
    C = Unit(1.0e+00, Charge, symbol="C", prefix_exp=0)
    kC = Unit(1.0e+03, Charge, symbol="C", prefix_exp=3)
    MC = Unit(1.0e+06, Charge, symbol="C", prefix_exp=6)
    GC = Unit(1.0e+09, Charge, symbol="C", prefix_exp=9)
    e = Unit(1.0e+00 * sc.e, Charge, symbol="e", prefix_exp=0)
    fT = Unit(1.0e-15, MagneticInduction, symbol="T", prefix_exp=-15)
    pT = Unit(1.0e-12, MagneticInduction, symbol="T", prefix_exp=-12)
    nT = Unit(1.0e-09, MagneticInduction, symbol="T", prefix_exp=-9)
    uT = Unit(1.0e-06, MagneticInduction, symbol="T", prefix_exp=-6)
    mT = Unit(1.0e-03, MagneticInduction, symbol="T", prefix_exp=-3)
    T = Unit(1.0e+00, MagneticInduction, symbol="T", prefix_exp=0)
    kT = Unit(1.0e+03, MagneticInduction, symbol="T", prefix_exp=3)
    MT = Unit(1.0e+06, MagneticInduction, symbol="T", prefix_exp=6)
    GT = Unit(1.0e+09, MagneticInduction, symbol="T", prefix_exp=9)
    TT = Unit(1.0e+12, MagneticInduction, symbol="T", prefix_exp=12)
    PT = Unit(1.0e+15, MagneticInduction, symbol="T", prefix_exp=15)
    pG = Unit(1.0e-12 * 1e-4, MagneticInduction, symbol="G", prefix_exp=-12)
    nG = Unit(1.0e-09 * 1e-4, MagneticInduction, symbol="G", prefix_exp=-9)
    uG = Unit(1.0e-06 * 1e-4, MagneticInduction, symbol="G", prefix_exp=-6)
    mG = Unit(1.0e-03 * 1e-4, MagneticInduction, symbol="G", prefix_exp=-3)
    G = Unit(1.0e+00 * 1e-4, MagneticInduction, symbol="G", prefix_exp=0)
    kG = Unit(1.0e+03 * 1e-4, MagneticInduction, symbol="G", prefix_exp=3)
    MG = Unit(1.0e+06 * 1e-4, MagneticInduction, symbol="G", prefix_exp=6)
    GG = Unit(1.0e+09 * 1e-4, MagneticInduction, symbol="G", prefix_exp=9)
    TG = Unit(1.0e+12 * 1e-4, MagneticInduction, symbol="G", prefix_exp=12)
    PG = Unit(1.0e+15 * 1e-4, MagneticInduction, symbol="G", prefix_exp=15)
    EG = Unit(1.0e+18 * 1e-4, MagneticInduction, symbol="G", prefix_exp=18)
